apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-11-04T14:42:50.917730356Z"
    description: A Helm chart for Kubernetes
    digest: 5c0cf87eecc787c65df6a779b780ca6383f059d35aad0c0c70f8805cc8630e6b
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://kubefleet-dev.github.io/kubefleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-02-20T23:21:54.648772096Z"
    description: A Helm chart for hub agent
    digest: 93a91120b3cd1c28bdd85f2465788a9dcec3096a48c91da92c89aba13978dcc2
    name: hub-agent
    type: application
    urls:
    - https://kubefleet-dev.github.io/kubefleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2026-02-20T23:21:54.64928927Z"
    description: Helm chart for member agent.
    digest: 4fffb12b5ef532c0ca0fa24816f32a4b6c0371c01aa7cee84e88d2001291d63e
    name: member-agent
    type: application
    urls:
    - https://kubefleet-dev.github.io/kubefleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2026-02-20T23:21:54.642442145Z"
