apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-11-04T14:42:50.917730356Z"
    description: A Helm chart for Kubernetes
    digest: 5c0cf87eecc787c65df6a779b780ca6383f059d35aad0c0c70f8805cc8630e6b
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://kubefleet-dev.github.io/kubefleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-02-02T00:30:43.519728011Z"
    description: A Helm chart for hub agent
    digest: 9722a705dc685a5473bd390d599becf263269232c624033dd02c77cac0f9f49d
    name: hub-agent
    type: application
    urls:
    - https://kubefleet-dev.github.io/kubefleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2026-02-02T00:30:43.520254852Z"
    description: Helm chart for member agent.
    digest: 3c088953832996f32df0ecb41268e4b2b50cf715c9edb4defec054e01a647589
    name: member-agent
    type: application
    urls:
    - https://kubefleet-dev.github.io/kubefleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2026-02-02T00:30:43.51440197Z"
