apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-11-04T14:42:50.917730356Z"
    description: A Helm chart for Kubernetes
    digest: 5c0cf87eecc787c65df6a779b780ca6383f059d35aad0c0c70f8805cc8630e6b
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://kubefleet-dev.github.io/kubefleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-02-20T19:53:13.554465086Z"
    description: A Helm chart for hub agent
    digest: f3efa729fd23ca803e4b14d43b4874388c630d14c33e0838f1d38c10e61a10cb
    name: hub-agent
    type: application
    urls:
    - https://kubefleet-dev.github.io/kubefleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2026-02-20T19:53:13.554930044Z"
    description: Helm chart for member agent.
    digest: 892ab6aac4679cc0a9210e8f3fdf284df926a4103dd53cfa53bd0f73d016075f
    name: member-agent
    type: application
    urls:
    - https://kubefleet-dev.github.io/kubefleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2026-02-20T19:53:13.547310343Z"
