apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-11-04T14:42:50.917730356Z"
    description: A Helm chart for Kubernetes
    digest: 5c0cf87eecc787c65df6a779b780ca6383f059d35aad0c0c70f8805cc8630e6b
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://kubefleet-dev.github.io/kubefleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-12-15T00:13:46.348416317Z"
    description: A Helm chart for hub agent
    digest: 58d580e6178956e0a1fef24bed0019c609a7d0d156b9990c2b117416bec2bbf3
    name: hub-agent
    type: application
    urls:
    - https://kubefleet-dev.github.io/kubefleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2025-12-15T00:13:46.348892515Z"
    description: Helm chart for member agent.
    digest: 37f72feba17a593fad82722ee7ef19ec3694e124723e6954835dc26ad9e4e4d5
    name: member-agent
    type: application
    urls:
    - https://kubefleet-dev.github.io/kubefleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-15T00:13:46.342174786Z"
