apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-11-04T14:42:50.917730356Z"
    description: A Helm chart for Kubernetes
    digest: 5c0cf87eecc787c65df6a779b780ca6383f059d35aad0c0c70f8805cc8630e6b
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://kubefleet-dev.github.io/kubefleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-02-02T00:22:11.50528482Z"
    description: A Helm chart for hub agent
    digest: 1db46d784c0b897f7f583ee1546b39315f72a2870f094bb683564e4e133799ab
    name: hub-agent
    type: application
    urls:
    - https://kubefleet-dev.github.io/kubefleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2026-02-02T00:22:11.50577108Z"
    description: Helm chart for member agent.
    digest: fdca4b692306f447f5d4d28dc2ccff126d79a67dc2f6ec1609e1b189472998ab
    name: member-agent
    type: application
    urls:
    - https://kubefleet-dev.github.io/kubefleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2026-02-02T00:22:11.499466603Z"
